### PR TITLE
Unsigned integers are now endian flipped when read if they are read o…

### PR DESCRIPTION
**Pull request by JLWalsh**
…n a little endian machine

Now all values represented in the bytecode will be in the big endian format.

### CODE REVIEW

**Comment by SafelySwift** [comment]
Do you want to use extra bits as a Boolean to determine whether manual control of endian representation is wanted? 

For example, I run a little median machine but if they are converted to big endian it will not be stored correctly.

**Comment by SafelySwift** [comment]
As an example, I might use this as assembly for [Swizzle](), which (when memory management features are added) allows the user to customize the endian-ness of pointers.

**Comment by JLWalsh** [comment]
> For example, I run a little median machine but if they are converted to big endian it will not be stored correctly.

They will be stored correctly. When the value is read on a little endian machine, it is indeed incorrect. But it is then flipped and so it becomes the correct value. That's all that is needed for this VM to work on little endian machines!

**Comment by SafelySwift** [comment]
I see

**Pull request merged**
